SurfClub/Models/DbModels/Post.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SurfClub.Models.DbModels
{
    public class Post
    {
        public int Id { get; set; }
        public String Text { get; set; }
        public Guid? Photo { get; set; }
        public DateTime PublishDate { get; set; }
        public virtual User Author { get; set; }
    }
}

SurfClub/Models/DbModels/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SurfClub.Models.DbModels
{
    public class User
    {
        public int Id { get; set; }
        public String Nickname { get; set; }
        public String Email { get; set; }
        public String Password { get; set; }
        public String Surname { get; set; }
        public String Name { get; set; }
        public Guid Photo { get; set; }
        public String Contact { get; set; }
        public String AboutMe { get; set; }
        public String Progress { get; set; }
    }
}

SurfClub/Models/SurfClubDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SurfClub.Models.DbModels;
using Microsoft.EntityFrameworkCore;

namespace SurfClub.Models
{
    public class SurfClubDbContext : DbContext
    {
        public DbSet<Post> Posts { get; set; }
        public DbSet<User> Users { get; set; }
        public SurfClubDbContext(DbContextOptions options) : base(options)
        {
            Database.EnsureCreated();
        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>().HasData(
               new User
               {
                   Id = 1,
                   Nickname = "TestUser",
                   Password = "TestPassword",
                   Photo = new Guid("498d7e21-cb9b-43a6-9e5b-37fcb41e273f")
               });
        }
    }
}

SurfClub/Models/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SurfClub.Models.ViewModels
{
    public class LoginViewModel
    {
        [Required(ErrorMessage = "Псевдоним обязателен")]
        [MaxLength(20), MinLength(3, ErrorMessage = "Минимальная длина 3 символа")]

        public String Nickname { get; set; }

        [Required(ErrorMessage = "Пароль обязателен")]
        [MaxLength(20), MinLength(3, ErrorMessage = "Минимальная длина 3 символа")]
        public String Password { get; set; }
        public bool RemoveName { get; set; }
    }
}

SurfClub/Controllers/FeedController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SurfClub.Helpers;
using SurfClub.Models;
using SurfClub.Models.DbModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace SurfClub.Controllers
{
    public class FeedController : Controller
    {
        private readonly SurfClubDbContext dbContext;

        public FeedController(SurfClubDbContext dbContext)
        {
            this.dbContext = dbContext;
        }


        public IActionResult Index()
        {
            var posts2 = dbContext.Posts
                 .Include(c => c.Author)
                 .OrderBy(c => c.PublishDate).ToArray();
            ViewBag.Posts = posts2;
            return View();
        }


        [HttpPost]
        public IActionResult AddPost(Post model, IFormFile ImageData)
        {
            if (string.IsNullOrEmpty(model.Text) && ImageData == null)
            {
                var posts1 = dbContext.Posts
                 .Include(c => c.Author)
                 .OrderBy(c => c.PublishDate).ToArray();
                ViewBag.Posts = posts1;
                return View("Index", model);
            }


            if (ImageData != null)
            {
                ImageHelper helper = new ImageHelper();
                model.Photo = ImageHelper.UploadImage(ImageData);
            }

            model.PublishDate = DateTime.Now;

            var UserId = HttpContext.Session.GetInt32("UserId").Value; // может быть пустым
            var user = dbContext.Users.FirstOrDefault(c => c.Id == UserId); // может быть пустым


            model.Author = user;

            dbContext.Posts.Add(model);
            dbContext.SaveChanges();

            var posts = dbContext.Posts
                 .Include(c => c.Author)
                 .OrderBy(c => c.PublishDate).ToArray();
            ViewBag.Posts = posts;

            return View("Index");
        }

    }
}

SurfClub/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SurfClub.Models.ViewModels;
using SurfClub.Models;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace SurfClub.Controllers
{
    public class LoginController : Controller
    {
        private readonly SurfClubDbContext dbContext;
        public LoginController(SurfClubDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel model)
        {
            if(ModelState.IsValid)
            {
                // проверить, есть ли пользователь в базе
                var user= dbContext.Users.FirstOrDefault(c => c.Nickname == model.Nickname && c.Password==model.Password);
                if (user == null)
                {
                    ModelState.AddModelError(string.Empty, "Неверный псевдоним или пароль!");
                }
                else
                {
                    //авторизовать на сайте, что-то сделать
                    var claims = new List<Claim>
            {
                new Claim(ClaimsIdentity.DefaultNameClaimType, user.Id.ToString())
            };

                    var authProp = new AuthenticationProperties();
                    // если стоит галка - запоминамем пользователя
                    if (model.RemoveName)
                    {
                        authProp.IsPersistent = true;
                        authProp.ExpiresUtc = DateTime.UtcNow.AddHours(2);
                    }

                    // создаем объект ClaimsIdentity
                    ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType, ClaimsIdentity.DefaultRoleClaimType);
                    // установка аутентификационных куки
                    HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(id), authProp);

                    HttpContext.Session.SetString("NickName", user.Nickname);
                    HttpContext.Session.SetString("Photo", user.Photo.ToString());
                    HttpContext.Session.SetInt32("UserId", user.Id);

                    return RedirectToAction("Index", "Feed");
                }
            }

            return View("Index", model);
        }
        public IActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Feed");
        }

    }
}

SurfClub/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SurfClub.Controllers
{
    public class RegisterController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SurfClub/Views/Feed/Index.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@HttpContextAccessor.HttpContext.Session.GetString("NickName")
<br>
@HttpContextAccessor.HttpContext.Session.GetString("Photo")
<br>
@HttpContextAccessor.HttpContext.Session.GetInt32("UserId")

@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    var userId = HttpContextAccessor.HttpContext.Session.GetInt32("UserId");
}

@model SurfClub.Models.DbModels.Post
@using SurfClub.Helpers


@if (userId != null)
{
    <form asp-controller="Feed" asp-action="AddPost"
          method="post" enctype="multipart/form-data">

        <div class="card">
            <div class="card-header">Добавление нового поста</div>
            <div class="card-body">
            <div class="form-group">
                <label asp-for="Text">Введите текст</label>
                <textarea asp-for="Text" rows="10" cols="100"></textarea>
                <span asp-validation-for="Text"></span>
            </div>

            <div class="form-group">
                <input type="file"
                       accept=".jpg,.jpeg,.png"
                       name="imageData" />
            </div>

            <div class="form-group">
                <input type="submit" value="Добавить" />
            </div>
            </div>

        </div>
    </form>
     
}


@foreach (var post in ViewBag.Posts)
{



<div class="card">

</div>
        <div class="card-header">
            @{
                var userPhoto = ImageHelper.GetUrl(post.Author.Photo);
                if (userPhoto != null)
                {

                    <img class ="" src="@Url.Content(userPhoto)" width="40" />
                }
            }

            @post.Author.Nickname

            @post.PublishDate
        </div>
        <div class="card-body">
            @post.Text

            @{
                var photoUrl = ImageHelper.GetUrl(post.Photo);
                if (photoUrl != null)
                {

                    <img class="" src="@Url.Content(photoUrl)" width="800" />
                }
            }
       
    </div>

}

SurfClub/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SurfClub/Views/Login/Index.cshtml
@model SurfClub.Models.ViewModels.LoginViewModel


@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form asp-controller="Login" asp-action="Login" asp-antiforgery="true">
    <div class="card">
        <div class="card-header">Авторизация</div>
        <div class="card-body">

            <div class="form-group">
                <label asp-for="Nickname"> Псевдоним </label>
                <input type="text" asp-for="Nickname" />
                <span asp-validation-for="Nickname"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password"> Пароль </label>
                <input type="password" asp-for="Password" />
                <span asp-validation-for="Password"></span>
            </div>

            <div class="form-group">
                <label asp-for="RemoveName"> Запомнить пароль </label>
                <input type="checkbox" asp-for="RemoveName" />
                <span asp-validation-for="RemoveName"></span>
            </div>

            <div class="validation" asp-validation-summary="ModelOnly"></div>

            <div class="form-group">
                <input type="submit" value="Войти" />
            </div>
        </div>
    </div>
    Нет аккаунта?<a class="btn btn-info" asp-controller="Register" asp-action="Index">Зарегистрироваться</a>

</form>

SurfClub/Views/Register/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Register
регистрацию доделаем в четверг

SurfClub/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using SurfClub.Helpers
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    var userId = HttpContextAccessor.HttpContext.Session.GetInt32("UserId");
    var nickName = HttpContextAccessor.HttpContext.Session.GetString("NickName");
    var photo = HttpContextAccessor.HttpContext.Session.GetString("Photo");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SurfClub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container logobg">
                <a class="navbar-brand" asp-area="" asp-controller="Feed" asp-action="Index">
                    <img src="~/img/logo.jpg" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @if (userId == null)
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Вход</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Index">Регистрация</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                <ul class="navbar-nav">
                    <div>
                        @{
                            var userPhoto = ImageHelper.GetUrl(new Guid(photo));
                            if (userPhoto != null)
                            {

                                <img class="" src="@Url.Content(userPhoto)" width="40" />
                            }
                        }
                    </div>

                    <li class="nav-item">
                        @nickName
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout"><img src="~/img/imgpsh_fullsize_anim.png" /></a>
                    </li>
                </ul>
                  }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>